# Abgabe 3 Mark Nagengast Porro, Tim Schwabe

In [56]:
import numpy as np

## Aufgabe 1

In [57]:
def RELU(x):
    return max(0,x)

In [58]:
def sigmoid(x):
    return 1/(1+(np.math.e)**(-x))

In [59]:
def createTrainingData(batch_size):

    data = np.array([[0,0],
                     [0,1],
                     [1,0],
                     [1,1]])
    truth = np.array([[0],[1],[1],[0]])
    
    training_data = []
    target = []
    while(batch_size > 0):
        index = np.random.randint(4)
        training_data.append(data[index])
        target.append(truth[index])
        batch_size -= 1
    return np.array(training_data), np.array(target)

train, target = createTrainingData(10)
print(train)
print(target)

[[1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [1 0]]
[[0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]]


## Aufgabe 2

In [60]:
class NN():

    def __init__(self, training_data, target_data,hidden_layers):

        self.training_data = training_data
        self.target_data = target_data

        self.weights = [np.random.uniform(size=(2,4))]
        while(hidden_layers > 1):
            self.weights.append(np.random.uniform(size=(4,16)))
            hidden_layers -=1
        self.weights.append(np.random.uniform(size=(1,4)))
        print(self.weights)


    def ReLU(self,x):
        return x * (x > 0) 
    
    def sigmoid(self, x):
        return 1/(1+(np.math.e)**(-np.array(x)))
    
    def forward(self, x):
        for i in range(len(self.weights)-1):
            product = np.dot(x, self.weights[i])
            print(product) # shape (1,4)
            x = self.ReLU(np.array(product))
        return self.sigmoid(np.dot(self.weights[1], x))

    def training(self):

        for i in range(len(self.training_data)):
            print(self.training_data[i])
            print(self.forward(self.training_data[i]))
        

test = NN(train,target,1)
test.training()

[array([[0.24084789, 0.44266231, 0.19809295, 0.43411779],
       [0.58630744, 0.90608086, 0.34061683, 0.25462053]]), array([[0.44119897, 0.00208509, 0.35320315, 0.20267821]])]
[1 1]
[0.82715533 1.34874317 0.53870979 0.68873832]
[0.66765957]
[0 0]
[0. 0. 0. 0.]
[0.5]
[1 0]
[0.24084789 0.44266231 0.19809295 0.43411779]
[0.56589893]
[1 1]
[0.82715533 1.34874317 0.53870979 0.68873832]
[0.66765957]
[0 1]
[0.58630744 0.90608086 0.34061683 0.25462053]
[0.60646583]
[1 1]
[0.82715533 1.34874317 0.53870979 0.68873832]
[0.66765957]
[0 1]
[0.58630744 0.90608086 0.34061683 0.25462053]
[0.60646583]
[1 0]
[0.24084789 0.44266231 0.19809295 0.43411779]
[0.56589893]
[1 1]
[0.82715533 1.34874317 0.53870979 0.68873832]
[0.66765957]
[1 0]
[0.24084789 0.44266231 0.19809295 0.43411779]
[0.56589893]
