# Abgabe 3 Mark Nagengast Porro, Tim Schwabe

In [21]:
import numpy as np

## Aufgabe 1

In [22]:
def RELU(x):
    return max(0,x)

In [23]:
def sigmoid(x):
    return 1/(1+(np.math.e)**(-x))

In [24]:
def createTrainingData(batch_size):

    data = np.array([[0,0],
                     [0,1],
                     [1,0],
                     [1,1]])
    truth = np.array([[0],[1],[1],[0]])
    
    training_data = []
    target = []
    while(batch_size > 0):
        index = np.random.randint(4)
        training_data.append(data[index])
        target.append(truth[index])
        batch_size -= 1
    return np.array(training_data), np.array(target)

train, target = createTrainingData(10)
print(train)
print(target)

[[1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 1]]
[[1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]]


## Aufgabe 2

In [25]:
class NN():

    def __init__(self, training_data, target_data,hidden_layers):

        self.training_data = training_data
        self.target_data = target_data

        self.weights = [np.random.uniform(size=(2,4))]
        while(hidden_layers > 1):
            self.weights.append(np.random.uniform(size=(4,16)))
            hidden_layers -=1
        self.weights.append(np.random.uniform(size=(4,1)))
        print(self.weights)


    def ReLU(self,x):
        return x * (x > 0) 
    
    def sigmoid(self, x):
        return 1/(1+(np.math.e)**(-np.array(x)))
    
    def forward(self, x):
        for i in range(len(self.weights)-1):
            product = np.dot(x, self.weights[i])
            print(product) # shape (1,4)
            x = self.ReLU(np.array(product))
        return self.sigmoid(np.dot(self.weights[1],x))

    def training(self):

        for i in range(len(self.training_data)):
            print(self.training_data[i])
            self.forward(self.training_data[i])
        

test = NN(train,target,1)
test.training()

[array([[0.38595531, 0.74759057, 0.27099038, 0.98749689],
       [0.72194527, 0.24188014, 0.3167798 , 0.02700763]]), array([[0.29275879],
       [0.14259706],
       [0.16243149],
       [0.38125868]])]
[1 0]
[0.38595531 0.74759057 0.27099038 0.98749689]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.