In [647]:
import numpy as np
from tqdm import tqdm

In [648]:
class NN():

    def __init__(self):

        self.data = np.array([[0,0],
                              [0,1],
                              [1,0],
                              [1,1]])
        self.target = np.array([[0],[1],[1],[0]])
        
        self.weights = [np.random.uniform(size=(2,2))]
        self.weights.append(np.random.uniform(size=(2,1)))

        #print(self.weights)

    def ReLU(self,x):
        return x * (x > 0) 
    
    def bcel(self, y, y_hat):
        return -(y*np.log(y_hat) + (1-y) * np.log(1-y_hat))
    
    def drv_loss_start(self, y, y_hat):
        return 1 / (1-y_hat) if y == 0 else -1 / y_hat

    def drv_loss(self, y, y_hat):
        return y_hat-y
    
    #def drv_sigmoid(self, z):
    #    return self.sigmoid(z) * (1-self.sigmoid(z))
    
    def drv_sigmoid(self, sigmoid_value):
        return sigmoid_value * (1-sigmoid_value)
    
    def drv_ReLU(self, z):
        return 1 * (z > 0)

    def sigmoid(self,x):
        return 1/(1+np.power((np.math.e),(-x)))
    
    def execute(self,x):
        result,_,_ = self.forward_pass(x)
        return np.round(result)
    
    def forward_pass(self,x):
        x = np.array(x)
        #print(x)
        z1 = x.dot(self.weights[0])
        #print(z1)
        hidden = self.ReLU(z1)
        #print(hidden)
        z2 = hidden.dot(self.weights[1])
        #print(z2)
        return self.sigmoid(z2), hidden, z1
    
    def backward_pass(self,x,y):
        alpha = 0.01
        y_hat, hidden, z1 = self.forward_pass(x)
        self.weights[1] = self.weights[1] - (alpha * self.drv_loss_start(y,y_hat)*self.drv_sigmoid(sigmoid_value=y_hat) * hidden).reshape(2,1)
        
        self.weights[0] = self.weights[0] - (alpha * self.drv_loss(y,y_hat) * self.weights[1].dot(x.reshape(1,2)).dot(self.drv_ReLU(z1)))
        
    def accuracy(self):
        counter = 0
    
        for i in range(len(self.data)):
            if(self.execute(self.data[i]) == self.target[i]):
                counter += 1
        loss = 0
        for i in range(len(self.data)):
            loss += self.bcel(self.target[i],self.forward_pass(self.data[i])[0])

        return counter / len(self.data), loss
     
    def train(self,epochs,batch_size):
        
        index = np.random.randint(4,size=batch_size)
        acc = 0
        for epoch in range(epochs):
            np.random.shuffle(index)
            for i in tqdm(index,desc="Epoch: " + str(epoch)): 
                self.backward_pass(self.data[i],self.target[i])
            acc, loss =  self.accuracy()
            #print("Current accuracy: " +f"{acc*100}%")
            #print("Current loss: " +f"{loss}")
            #print(self.weights)

        print(acc)

In [649]:
nn = NN()

nn.forward_pass([0,1])

(array([0.52217972]),
 array([0.79224792, 0.20649944]),
 array([0.79224792, 0.20649944]))

In [650]:
nn.train(1000,200)

Epoch: 0:   0%|          | 0/200 [00:00<?, ?it/s]C:\Users\timds\AppData\Local\Temp\ipykernel_18956\3603037872.py:23: RuntimeWarning: divide by zero encountered in divide
  return 1 / (1-y_hat) if y == 0 else -1 / y_hat
C:\Users\timds\AppData\Local\Temp\ipykernel_18956\3603037872.py:58: RuntimeWarning: invalid value encountered in multiply
  self.weights[1] = self.weights[1] - (alpha * self.drv_loss_start(y,y_hat)*self.drv_sigmoid(sigmoid_value=y_hat) * hidden).reshape(2,1)
Epoch: 999: 100%|██████████| 200/200 [00:00<00:00, 28678.02it/s]

0.0
