In [484]:
import numpy as np
from tqdm import tqdm
from time import sleep

In [485]:
class NN():

    def __init__(self, hiddenLayer_neuron = 2,learning_rate = 0.1):

        self.data = np.array([[0,0],
                              [0,1],
                              [1,0],
                              [1,1]])
        self.target = np.array([[0],[1],[1],[0]])

        self.hl_neuron = hiddenLayer_neuron
        
        self.w_hidden = np.random.uniform(size=(2,self.hl_neuron))
        self.w_out = np.random.uniform(size=(self.hl_neuron,1))

        self.b_hidden = np.random.uniform(size=(1,self.hl_neuron))
        self.b_out = np.random.uniform(size=(1,1))

        self.z0s = []
        self.z1s = []

        self.lr = learning_rate

        print("Init: ")
        self.print_weights()

    def ReLU(self,x):
        return x * (x > 0) 
    
    def bcel(self, y, y_hat):
        return -(y*np.log(y_hat) + (1-y) * np.log(1-y_hat))
    
    def drv_loss_start(self, y, y_hat):
        return 1 / (1-y_hat) if y == 0 else -1 / y_hat

    def drv_loss(self, y, y_hat):
        return y_hat-y
    
    def drv_sigmoid(self, z):
        return self.sigmoid(z) * (1-self.sigmoid(z))
    
    '''def drv_sigmoid(self, sigmoid_value):
        return sigmoid_value * (1-sigmoid_value)'''
    
    def drv_ReLU(self, z):
        return 1 * (z > 0)

    def sigmoid(self,x):
        return 1/(1 + np.exp(-x))
    
    def execute(self,x):
        result = self.sigmoid(self.forward_pass(x)[0])
        return np.round(result)
    
    def forward_pass(self,x):
        x = np.array(x)
        z0 = np.dot(x.T,self.w_hidden) + self.b_hidden
        print(z0)
        hidden = self.ReLU(z0)
        z1 = np.dot(hidden,self.w_out) + self.b_out
        return z1, z0
    

    def backward_pass(self,x,y):

        alpha = 0.1
        z1, z0 = self.z1s.pop(), self.z0s.pop()

        y_hat = self.sigmoid(z1)
        d1 = self.drv_loss_start(y,y_hat)*self.drv_sigmoid(z1)
        d0 = self.drv_loss(y,y_hat) * np.dot(self.drv_ReLU(z0),self.w_out)

        self.w_out -= alpha* np.dot(self.ReLU(z0).T,d1) 
        self.w_hidden -= alpha* np.dot(x.reshape(2,1),d0)

        self.b_out -= alpha*np.sum(d1, axis=0, keepdims=True)
        self.b_hidden -= alpha*np.sum(d0, axis=0, keepdims=True)
        
    def print_weights(self):
        print("W_hidden: " + str(self.w_hidden)) 
        print("B_hidden: " + str(self.b_hidden)) 
        print("W_out: " + str(self.w_out)) 
        print("B_out: " + str(self.b_out), end="\n\n")


    def accuracy(self):
        counter = 0
    
        for i in range(len(self.data)):
            if(self.execute(self.data[i]) == self.target[i]):
                counter += 1
        loss = 0
        for i in range(len(self.data)):
            loss += self.bcel(self.target[i],self.sigmoid(self.forward_pass(self.data[i])[0]))

        return counter / len(self.data), loss / len(self.data)
     
    def train(self,epochs, batch_size, fast_train = False):

        if epochs > 0:
            for epoch in range(epochs):
                index = np.random.randint(4,size=batch_size)
                for i in index:
                    z1, z0 = self.forward_pass(self.data[i])
                    self.z0s.append(z0)
                    self.z1s.append(z1)

                self.z1s.reverse()
                self.z0s.reverse()

                if not fast_train:

                    for i in tqdm(index,desc="Epoch: " + str(epoch)): 
                        self.backward_pass(self.data[i],self.target[i])
                        sleep(.1)
                    acc, loss =  self.accuracy()
                    print("Current accuracy: " +f"{acc*100}%")
                    print("Current loss: " +f"{loss}")
                
                else:
                    for i in index:
                        self.backward_pass(self.data[i],self.target[i])
                    acc, loss =  self.accuracy()
            
            print("Current accuracy: " +f"{acc*100}%")
            print("Current loss: " +f"{loss}")

        
        else:
            epoch = 0
            acc = 0
            while acc  != 1:
                index = np.random.randint(4,size=batch_size)
                for i in index:
                    z1, z0 = self.forward_pass(self.data[i])
                    self.z0s.append(z0)
                    self.z1s.append(z1)

                self.z1s.reverse()
                self.z0s.reverse()

                if not fast_train:

                    for i in tqdm(index,desc="Epoch: " + str(epoch)): 
                        self.backward_pass(self.data[i],self.target[i])
                        sleep(.1)
                    acc, loss =  self.accuracy()
                    print("Current accuracy: " +f"{acc*100}%")
                    print("Current loss: " +f"{loss}")
                
                else:
                    for i in index:
                        self.backward_pass(self.data[i],self.target[i])
                    acc, loss =  self.accuracy()
                    print("Current accuracy: " +f"{acc*100}%")
                    print("Current loss: " +f"{loss}")
                epoch += 1
        print("Epochs trained: " + str(epoch))
        self.print_weights()

        return acc



        
            

In [486]:
nn = NN(4,learning_rate=0.00001)

Init: 
W_hidden: [[0.49117521 0.73442995 0.90891559 0.4789106 ]
 [0.96325737 0.60019308 0.9278356  0.61920373]]
B_hidden: [[0.36671979 0.53911948 0.82064756 0.99800239]]
W_out: [[0.96053171]
 [0.8293725 ]
 [0.80455441]
 [0.09888151]]
B_out: [[0.5881767]]



In [487]:
nn.train(epochs = -1,batch_size= 2,fast_train=True)

[[0.857895   1.27354943 1.72956314 1.476913  ]]


ValueError: shapes (4,1) and (4,1) not aligned: 1 (dim 1) != 4 (dim 0)

In [ ]:
print(nn.execute([0,0]))
print(nn.execute([0,1]))
print(nn.execute([1,0]))
print(nn.execute([1,1]))

[[-0.17258183  0.53061269  0.01723316  0.13108194]]
[[0.]]
[[1.47944582 2.16063468 1.94008166 1.84856069]]
[[1.]]
[[-1.75212782 -1.09379707 -1.85328838 -1.08833044]]
[[1.]]
[[-0.10010017  0.53622492  0.06956012  0.62914832]]
[[0.]]
